# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import voice_phishing_pb2 as voice__phishing__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in voice_phishing_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VoicePhishingAnalysisStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Analyze = channel.unary_unary(
                '/voice_phishing.VoicePhishingAnalysis/Analyze',
                request_serializer=voice__phishing__pb2.AnalyzeRequest.SerializeToString,
                response_deserializer=voice__phishing__pb2.AnalyzeResponse.FromString,
                _registered_method=True)


class VoicePhishingAnalysisServicer:
    """Missing associated documentation comment in .proto file."""

    def Analyze(self, request, context):
        """F-01/F-02/F-05: analyze_call_pattern(MCP 툴)/POST /api/v1/analyze(REST)와 동일한
        판정을 gRPC로 제공한다.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VoicePhishingAnalysisServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Analyze': grpc.unary_unary_rpc_method_handler(
                    servicer.Analyze,
                    request_deserializer=voice__phishing__pb2.AnalyzeRequest.FromString,
                    response_serializer=voice__phishing__pb2.AnalyzeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'voice_phishing.VoicePhishingAnalysis', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('voice_phishing.VoicePhishingAnalysis', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VoicePhishingAnalysis:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Analyze(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voice_phishing.VoicePhishingAnalysis/Analyze',
            voice__phishing__pb2.AnalyzeRequest.SerializeToString,
            voice__phishing__pb2.AnalyzeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
