# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: voice_phishing.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'voice_phishing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14voice_phishing.proto\x12\x0evoice_phishing\"$\n\x0e\x41nalyzeRequest\x12\x12\n\ntranscript\x18\x01 \x01(\t\"U\n\x0f\x44\x65tectedPattern\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\x12\x16\n\x0e\x63\x61tegory_label\x18\x02 \x01(\t\x12\x18\n\x10matched_keywords\x18\x03 \x03(\t\"y\n\x0bSimilarCase\x12\x0f\n\x07\x63\x61se_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\x12\x0f\n\x07summary\x18\x04 \x01(\t\x12\x13\n\x0bsource_note\x18\x05 \x01(\t\x12\x12\n\nsimilarity\x18\x06 \x01(\x01\"\xac\x02\n\x0f\x41nalyzeResponse\x12:\n\x11\x64\x65tected_patterns\x18\x01 \x03(\x0b\x32\x1f.voice_phishing.DetectedPattern\x12\x15\n\rpattern_count\x18\x02 \x01(\x05\x12\x1b\n\x13has_risk_indicators\x18\x03 \x01(\x08\x12\x12\n\nrisk_score\x18\x04 \x01(\x05\x12\x12\n\nrisk_level\x18\x05 \x01(\t\x12\x1b\n\x13\x65xplanation_summary\x18\x06 \x01(\t\x12\x1b\n\x13\x65xplanation_reasons\x18\x07 \x03(\t\x12\x13\n\x0b\x65xplanation\x18\x08 \x01(\t\x12\x32\n\rsimilar_cases\x18\t \x03(\x0b\x32\x1b.voice_phishing.SimilarCase2c\n\x15VoicePhishingAnalysis\x12J\n\x07\x41nalyze\x12\x1e.voice_phishing.AnalyzeRequest\x1a\x1f.voice_phishing.AnalyzeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'voice_phishing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANALYZEREQUEST']._serialized_start=40
  _globals['_ANALYZEREQUEST']._serialized_end=76
  _globals['_DETECTEDPATTERN']._serialized_start=78
  _globals['_DETECTEDPATTERN']._serialized_end=163
  _globals['_SIMILARCASE']._serialized_start=165
  _globals['_SIMILARCASE']._serialized_end=286
  _globals['_ANALYZERESPONSE']._serialized_start=289
  _globals['_ANALYZERESPONSE']._serialized_end=589
  _globals['_VOICEPHISHINGANALYSIS']._serialized_start=591
  _globals['_VOICEPHISHINGANALYSIS']._serialized_end=690
# @@protoc_insertion_point(module_scope)
